version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app_data:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
    networks:
      - laravel

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./app_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - app
    networks:
      - laravel
    links:
      - app
    command: ["bash", "-c", "chown -R www-data:www-data /var/www/html && nginx -g 'daemon off;'"]

  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
